### ISSUE TITLE
Week 5: Project Assignment

### ISSUE THREAD

**Issue by KaterynPino** [rin3-spring-2021/KaterynPino_R4Us_Project#1]
Hi Charlie, 

Sorry for the delay with this week's project. I was having trouble with knitting. In the end, I can't do it in HTML format; I don't know why?. 

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'htmltools' 0.5.0 is already loaded, but >= 0.5.1 is required
Calls: <Anonymous> ... getNamespace -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted

Another question; How can I reorder the x coordinate of my plot to appears in ascendent order, 9, 10, 11, and 12, and not like 10, 11, 12, and 9? 

Thanks!

**Comment by charliejhadley** [comment]
Hey! I've answered your chart question here https://share.getcloudapp.com/Jru4DRD5

**Comment by KaterynPino** [comment]
Thanks for the feedback, Charlie!
install.packages("htmltools") works, now I can knit my file in this format. Thanks :)
